# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

jobs:
  - job: RunTests
    displayName: "Install Node.js and run tests"
    pool:
      vmImage: ubuntu-latest
    steps:  
      - task: NodeTool@0
        condition: succeededOrFailed()
        inputs:
          versionSpec: "16.x"
        displayName: "Node.js Installation"
      - task: DownloadSecureFile@1
        name: envFile
        inputs:
          secureFile: '.env'
      - task: CopyFiles@2
        inputs:
          sourceFolder: $(envFile.secureFilePath)
          targetFolder: $(System.DefaultWorkingDirectory)
      - script: | 
          npm install
          npm run allTests
        displayName: "Npm install and run API tests"
      - task: PublishPipelineArtifact@1
        condition: succeededOrFailed()
        inputs:
          targetPath: $(System.DefaultWorkingDirectory)/playwright-report
          artifactName: HtmlReport
        displayName: "Publish HTML report"
      - task: PublishPipelineArtifact@1
        condition: succeededOrFailed()
        inputs:
          targetPath: $(System.DefaultWorkingDirectory)/test-results
          artifactName: TestArtifacts
        displayName: "Publish Test Artifacts"
